[language.latex]
filetypes = ["latex"]
roots = ["header.tex"]
command = "/home/useredsa/bin/texlab"
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd-9", ".git"]
command = "clangd"
