[language.latex]
filetypes = ["latex"]
roots = ["header.tex"]
command = "/home/useredsa/bin/texlab"
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = [".ccls-root", "compile_commands.json", ".git"]
command = "ccls"
# kak-lsp does not support newText https://github.com/ul/kak-lsp/issues/40
args = ["--init={\"completion\":{\"detailedLabel\":false}}"]
