
###############################################################
# This configuration file lets you
# - define new commands
# - change the shortcut or triggering keys of built-in verbs
# - change the colors
# - set default values for flags
#
# Configuration documentation is available at
#     https://dystroy.org/broot
###############################################################

###############################################################
# Default flags
# You can set up flags you want broot to start with by
# default, for example `default_flags="ihp"` if you usually want
# to see hidden and gitignored files and the permissions (then
# if you don't want the hidden files you can launch `br -H`)
# A popular flag is the `g` one which displays git related info.
#
default_flags = ""

###############################################################
# Verbs and shortcuts

# If $EDITOR isn't set on your computer, you should either set it using
#  something similar to
#   export EDITOR=/usr/bin/nvim
#  or just replace it with your editor of choice in the 'execution'
#  pattern.
# Example:
#  execution = "/usr/bin/nvim {file}"
#
[[verbs]]
invocation = "edit"
key = "F2"
shortcut = "e"
execution = "$EDITOR {file}"
leave_broot = false

[[verbs]]
key = "ctrl-c"
execution = ":quit"

[[verbs]]
invocation = "create {subpath}"
execution = "$EDITOR {directory}/{subpath}"

[[verbs]]
invocation = "git_diff"
shortcut = "gd"
execution = "git diff {file}"

# If $PAGER isn't set on your computer, you should either set it
#  or just replace it with your viewer of choice in the 'execution'
#  pattern.
# Example:
#  execution = "less {file}"
[[verbs]]
name = "view"
invocation = "view"
execution = "$PAGER {file}"

# If you uncomment the two next shortcuts, the left
# and right arrow keys will be used to go to the parent
# directory or to open a selected one:
#
# [[verbs]]
# key = "left"
# execution = ":parent"
#
# [[verbs]]
# key = "right"
# execution = ":focus"

# Another popular set of shorctuts for going up and down:
#
# [[verbs]]
# key = "ctrl-j"
# execution = ":line_down"
#
# [[verbs]]
# key = "ctrl-k"
# execution = ":line_up"
#
# [[verbs]]
# key = "ctrl-d"
# execution = ":page_down"
#
# [[verbs]]
# key = "ctrl-u"
# execution = ":page_up"

# If you develop using git, you might like to often switch
# to the "git status" filter:
#
# [[verbs]]
# key = "ctrl-g"
# execution = ":toggle_git_status"

###############################################################
# Skin
# If you want to change the colors of broot,
# uncomment the following bloc and start messing
# with the various values.
# Note that some of those colors might not correcly
# render on terminals with low capabilities.
#

[skin]
default = "rgb(29, 40, 33) none"
tree = "rgb(168, 153, 132) none"
file = "rgb(212, 190, 152) none"
directory = "rgb(125, 174, 163) none bold"
exe = "rgb(169, 182, 101) none bold"
link = "rgb(137, 180, 130) none bold"
pruning = "rgb(168, 153, 132) none Italic"
# sparse = "red None"
perm__ = "rgb(212, 190, 152) None"
perm_r = "rgb(212, 190, 152) None"
perm_w = "rgb(212, 190, 152) None"
perm_x = "rgb(212, 190, 152) None"
owner = "rgb(212, 190, 152) none"
group = "rgb(212, 190, 152) none"
dates = "rgb(212, 190, 152) none"
selected_line = "none gray(3)"
char_match = "rgb(250, 189, 47) none"
# file_error = "Red none"
flag_label = "rgb(212, 190, 152) none"
flag_value = "rgb(255, 152, 0) none bold"
input = "rgb(212, 190, 152) none"
status_error = "rgb(212, 190, 152) rgb(234, 105, 98)"
# status_job = "ansi(220) gray(5)"
status_normal = "rgb(40, 40, 40) rgb(212, 190, 152)"
status_italic = "rgb(0, 0, 0) rgb(212, 190, 152) bold"
status_bold = "rgb(0, 0, 0) rgb(212, 190, 152) bold"
status_code = "rgb(0, 0, 0) rgb(212, 190, 152)"
# status_ellipsis = "none gray(3)"
scrollbar_track = "gray(3) none"
scrollbar_thumb = "rgb(212, 190, 152) none"
help_paragraph = "rgb(212, 190, 152) none"
help_bold = "rgb(169, 182, 101) none bold"
help_italic = "rgb(212, 190, 152) none italic"
help_code = "rgb(211, 134, 155) rgb(40, 40, 40)"
help_headers = "rgb(169, 182, 101) none"
# You may find other skins on
#  https://dystroy.org/broot/documentation/configuration/#colors
# for example a skin suitable for white backgrounds

