def config -docstring %{ config: Edit kakrc } %{ edit ~/.config/kak/kakrc }

# Basic Configuration ─────────────────────────────────────────────────────────

set global startup_info_version 20201901 # Only show update messages post v2020.08.04
set global scrolloff 1,5
set global tabstop 4
set global grepcmd 'rg --with-filename --column'

colorscheme-gruvbox-alpha

add-highlighter global/ show-matching
add-highlighter global/ number-lines
add-highlighter global/ regex '(\b|%|//|#)? ?(TODO|FIXME|XXX|NOTE)\b' 0:default+rb

hook global BufCreate .*\.(markdown|md|mkd) %{ set-option buffer filetype markdown }
hook global BufCreate .*\.(latex) %{ set-option buffer filetype latex }

hook global WinSetOption filetype=(c|cpp|latex|markdown) %{
    add-highlighter window/ wrap -indent -width 120 -marker …
}

# Plugins ─────────────────────────────────────────────────────────────────────

require-module plug

plug plug https://github.com/alexherbo2/plug.kak %{
    define-command -docstring %{
        plug-full-install: Installation of plugin plus execution of commands
    } plug-full-install %{
        plug-install
        plug-execute connect make install
        plug-execute lsp cargo build --release
    }
}

plug-core %{
}

#TODO plug-old "useredsa/pager.kak" noload do %{ ln -f bin/kak-man-pager bin/kak-pager ~/.local/bin }

plug-theme mysticaltutor "https://github.com/caksoylar/kakoune-mysticaltutor"

plug-theme dracula "https://github.com/alexherbo2/kakoune-dracula-theme"

plug-theme snow "https://github.com/caksoylar/kakoune-snow"

plug prelude "https://github.com/alexherbo2/prelude.kak"

plug terminal-mode "https://github.com/alexherbo2/terminal-mode.kak" %{
    map global user t ': enter-user-mode terminal<ret>' -docstring 'Terminal mode'
    require-module x11
    set global termcmd 'kitty sh -c'
}

plug bspwm tools/bspwm.kak %{
    set -add global windowing_modules bspwm
}

plug auto-pairs "https://github.com/alexherbo2/auto-pairs.kak" %[
    set-option global auto_pairs ( ) { }
]

plug smarttab "https://github.com/andreyorst/smarttab.kak" %{
    set global softtabstop 4
    hook global WinSetOption filetype=(c|cpp|asciidoctor|rust|markdown|kak|sh|perl|julia|latex|java) expandtab
    hook global WinSetOption filetype=(makefile|gas) noexpandtab
    hook global WinSetOption filetype=() smarttab
}

plug-old kakboard "https://github.com/lePerdu/kakboard" %{
    hook global WinCreate .* %{ kakboard-enable }
    # hook global WinDisplay .* %{ set window kakboard_copy_cmd "base64 | (printf '\033]52;c;!\033\a\033]52;c;'; cat; printf '\a') >""%val{client_env_TTY}""" }
}

plug-old kak-ansi "https://github.com/eraserhd/kak-ansi"

plug-old lsp "https://github.com/ul/kak-lsp" %{
    hook global WinSetOption filetype=(c|cpp|latex) lsp-enable-window

    set global lsp_diagnostic_line_error_sign '║'
    set global lsp_diagnostic_line_warning_sign '┊'
    set global lsp_auto_highlight_references true
    set global lsp_hover_anchor true
    set global lsp_hover_max_lines 3
    lsp-auto-hover-enable

    # lsp-inlay-diagnostics-enable global
    map global user l ': enter-user-mode lsp<ret>' -docstring 'Lsp mode'
}

plug connect "https://github.com/alexherbo2/connect.kak" %{
    require-module connect-rofi
    require-module connect-dolphin
    require-module connect-broot
    require-module connect-fzf
    alias global popup kitty-terminal-tab
    alias global repl-new bspwm-repl
}

plug explore "https://github.com/alexherbo2/explore.kak" %{
    alias global explore-files fzf-files
    alias global explore-buffers fzf-buffers
    explore-enable
}

plug batch "https://github.com/alexherbo2/batch.kak"

plug-old kakoune-phantom-selection "https://github.com/occivink/kakoune-phantom-selection" %{
    # face global PhantomSelection "default,rgba:72637216+g"
    face global PhantomSelection "%opt{alpha_fg},%opt{alpha_purple}"
    define-command -docstring %{
        phantom-group: Creates a phantom group of selections
    } -hidden phantom-group %{
        phantom-selection-add-selection
        map buffer normal <tab>   ': phantom-selection-iterate-next<ret>'
        map buffer insert <tab>   '<esc>: phantom-selection-iterate-next<ret>i'
        map buffer normal <s-tab> ': phantom-selection-iterate-prev<ret>'
        map buffer insert <s-tab> '<esc>: phantom-selection-iterate-prev<ret>i'
        map buffer normal <c-g>   ': phantom-ungroup<ret>'
        map buffer insert <c-g>   '<esc>: phantom-ungroup<ret>i'
    }
    define-command -docstring %{
        phantom-ungroup: Removes a phantom group of selections
    } -hidden phantom-ungroup %{
        phantom-selection-select-all
        phantom-selection-clear
        unmap buffer normal <tab>   ': phantom-selection-iterate-next<ret>'
          map buffer insert <tab>   '<tab>'
        unmap buffer normal <s-tab> ': phantom-selection-iterate-prev<ret>'
        unmap buffer insert <s-tab> '<esc>: phantom-selection-iterate-prev<ret>i'
        unmap buffer normal <c-g>   ': phantom-ungroup<ret>'
        unmap buffer insert <c-g>   '<esc>: phantom-ungroup<ret>i'
    }
    map global normal <c-g> ': phantom-group<ret><space>'
    map global insert <c-g> '<a-;>: phantom-group<ret><a-;><space>'
}

plug move-line "https://github.com/alexherbo2/move-line.kak" %{
    bam global '<a-;>' <a-up>   ': move-line-above<ret>'  # <a-up>   - Move line up
    bam global '<a-;>' <a-down> ': move-line-below<ret>'  # <a-down> - Move line down
}

plug dynamic-matching "https://github.com/useredsa/dynamic-matching.kak" %{
    dynamic-matching-dmatch-conf
    map global normal m ': enter-user-mode dmatch<ret>'
    map global normal M ': enter-user-mode Dmatch<ret>'
    map global user   m ': enter-user-mode -lock dmatch<ret>' -docstring "dmatch mode"
}

plug-old kakoune-mark "https://gitlab.com/fsub/kakoune-mark" %{
    bam global '<a-;>' <F8>   ': mark-word<ret>'                             # <F8>   - Mark(highlight) word under the cursor
    bam global '<a-;>' <a-F8> ': mark-pattern toggle "%val{selection}"<ret>' # <a-F8> - Mark(highlight) current selection
    bam global '<a-;>' <s-F8> ': mark-clear<ret>'                            # <s-F8> - Erase mark highlighters
}

plug-old kakoune-inc-dec 'https://gitlab.com/Screwtapello/kakoune-inc-dec' %{
    map global normal <plus>  ': inc-dec-modify-numbers + %val{count}<ret>'  # <plus>  - Increment number
    map global normal <minus> ': inc-dec-modify-numbers - %val{count}<ret>'  # <minus> - Decrement number
}

plug-old surround 'https://github.com/h-youhei/kakoune-surround' %|
    declare-user-mode surround
    map global surround s   ': surround<ret>'                 -docstring 'surround'
    map global surround c   ': change-surround<ret>'          -docstring 'change'
    map global surround d   ': delete-surround<ret>'          -docstring 'delete'
    map global surround t   ': select-surrounding-tag<ret>'   -docstring 'select tag'
    map global surround <"> ': surround<ret>"'                -docstring 'surround with ""'
    map global surround <'> ": surround<ret>'"                -docstring "surround with ''"
    map global surround <`> ': surround<ret>`'                -docstring 'surround with ``'
    map global surround <(> ': surround<ret>('                -docstring 'surround with ()'
    map global surround <{> ': surround<ret>{'                -docstring 'surround with {}'
    map global surround <[> ': surround<ret>['                -docstring 'surround with []'
    map global surround <<> ': surround<ret><'                -docstring 'surround with <>'
    map global user s       ': enter-user-mode surround<ret>' -docstring 'Surround mode'
|

plug-old auto-percent 'https://github.com/Delapouite/kakoune-auto-percent'

plug word-select "https://github.com/alexherbo2/word-select.kak" %{
    map global normal w     '<a-:>: word-select-next-word<ret>'
    map global normal <a-w> '<a-:>: word-select-next-big-word<ret>'
    map global normal b     '<a-:><a-;>: word-select-previous-word<ret>'
    map global normal <a-b> '<a-:><a-;>: word-select-previous-big-word<ret>'
}

plug-old text-objects "https://github.com/Delapouite/kakoune-text-objects" %{
    unmap global object v
    unmap global object d
    unmap global object o

    map global object a 'u' -docstring 'argument'
}

# Local kakrc ─────────────────────────────────────────────────────────────────

define-command -docstring %{
    kakrc-local: Edit local kakrc
} kakrc-local %{
    edit .kakrc.local
}

hook global BufCreate (.*/)?(\.kakrc\.local) %{
    set-option buffer filetype kak
}

try %{ source .kakrc.local }

