[language.latex]
filetypes = ["latex"]
roots = ["header.tex", "out"]
command = "/home/useredsa/bin/texlab"
[language.c_cpp]
filetypes = ["c", "cpp"]
roots = ["compile_commands.json", ".clangd"]
command = "clangd"
